-- Create a table for photos
create table photos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  url text not null,
  width integer,
  height integer,
  aspect_ratio numeric,
  filter_settings jsonb
);

-- Set up Row Level Security (RLS)
alter table photos enable row level security;

-- Create a policy that allows anyone to read photos
create policy "Public photos are viewable by everyone"
  on photos for select
  using ( true );

-- Create a policy that allows anyone to insert photos (for this demo)
create policy "Anyone can upload photos"
  on photos for insert
  with check ( true );

-- Create a policy that allows anyone to delete photos
create policy "Anyone can delete photos"
  on photos for delete
  using ( true );

-- Create a storage bucket for photos
insert into storage.buckets (id, name, public) values ('photos', 'photos', true);

-- Set up storage policies
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'photos' );

create policy "Anyone can upload"
  on storage.objects for insert
  with check ( bucket_id = 'photos' );

create policy "Anyone can delete"
  on storage.objects for delete
  using ( bucket_id = 'photos' );
